DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER
(
    CUSTOMER_ID VARCHAR(11) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    TEL VARCHAR(100),
    ADDR VARCHAR(100),
    GENDER VARCHAR(1),
    AGE NUMBER
);

DROP TABLE IF EXISTS CART;
CREATE TABLE CART
(
  ID SERIAL PRIMARY KEY,
  USER_ID NUMBER(20) DEFAULT NULL,
  SESSION_ID varchar(100) NOT NULL,
  TOKEN varchar(100) NOT NULL,
  STATUS NUMBER(6),
  FIRST_NAME varchar(50),
  MIDDLE_NAME varchar(50),
  LAST_NAME varchar(50),
  MOBILE varchar(15),
  EMAIL varchar(50),
  CITY varchar(50),
  PROVINCE varchar(50),
  COUNTRY varchar(50),
  CREATED_AT timestamp,
  UPDATED_AT timestamp,
  CONTENT varchar(500)
);

DROP TABLE IF EXISTS PRODUCTS;
CREATE TABLE PRODUCTS (
  ID NUMBER(11) PRIMARY KEY,
  NAME varchar(45) NOT NULL,
  PRICE NUMBER(11) NOT NULL,
  CATEGORY_ID NUMBER(11) NOT NULL,
  PICTURES varchar(200) DEFAULT NULL,
  DESCRIPTION varchar(800) DEFAULT NULL
);
